name: Compilation

on:
  pull_request:
    types: [opened]
  push:

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        configuration: ["Release", "Debug"]
      

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        dotnet publish Mvk.Launcher -p:PublishProfile={{matrix.configuration}} -o .publish/{{matrix.configuration}}/
        
    - name: Artifact Pack 
      uses: actions/upload-artifact@v2
      with:
        name: artifact${{matrix.configuration}}
        path: .publish/{{matrix.configuration}}/*.dll
