name: Tab Build

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        configuration: ["Release", "Debug"]
      

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        dotnet publish -p:PublishProfile={{matrix.configuration}}
        
    - name: Artifact Pack 
        uses: actions/upload-artifact@v2
        with:
          path: .publish/{{matrix.configuration}}/*.dll
